---
title: "JMJPFU-DAGSentiment-Process"
output: html_notebook


---

# JMJPFU
### 14-May-2017

This is a new work as directed by my Lord. This is based on a web of graphs to treat text data and then ultimately mine the semantics and connect it with the overall process of a domain.

This entails the following

1. Creating dictionaries ( Aspect, Phrases and idioms, Sentiments, Aspects)
2. Creating DAG's connecting dictionaries and sentiments. Sentiments are at the level of document & sentences
3. Two levels of models would be required. One to predict at the overall level, second to predict at each aspect level.
3. Creating an encoded DAG history of transactions which will connect various dictionaries and gives history of every transactions. This works on the concept like a block chain. The nuances of the sentiment and its connections with the process is encoded as a graph. - This is called encoded lineage
4. Connecting the intelligence extracted to the business process
5. A historical change in sentiments of various aspects with respect to property , location hierarchies.
6. Recommendations of suggested strategies to improve the sentiments.


### Core algorithm steps

1. Strip a document as per various sentences.
2. Note the number of sentences, number of words of  each document in a meta data graph.
3. Pick an aspect and then convolute through each word and look for degrees of sentiments associated with each aspect.
4. When a + is associated the overall sentiment become +ve. If a negative is attached to the +ve the whole sentiment becomes negative.
5. Recursively look at the evolution of sentiments over sentence and then note this evolution in the graph history. The idea is to recreate the sentiment from the history at any point in time
6.Once one sentence is recursively searched, look for adjoining sentences and create individual sentiment DAGs. See if the individual sentence DAGs also can be connected. 
7. Capture the sentiment DAGs as features in a feature data frame
8. Prediction to happen at two levels. One at document level to find the overall sentiment and then at the Aspect level to reveal the aspect sentiment.
9. Connect the aspect to menu items and other details so that we are able to pip point exactly where the sentiment is pointed at. This also can be encoded as graphs.
10. In terms of metadata collection for each store, menu , locations, names of people, name of restaurants, Competitors information ( including cooking at home) are all captured.


# JMJPFU
### 11-June-2017

Let us now look at this from a process perspective.

1. Take a whole document
2. Find the number of sentences in the document
3. For each document extract the features, aspect by aspect
4. Consolidate all the aspect based sentiment DAG for a document
5. Consolidate all DAGS for a document i.e consolidate the DAGS of each sentences
6. Consolidate DAGS for all documents


```{r}
# Start first hierarchy
# Starting a Hotel level DAG to consolidate all reviews for a hotel
hotDag <- list()

for(i in 1: nrow(Hotel_reviews)){
  # Taking one document at a time
  hotText <- Hotel_reviews[i,1] 
  # Doing the split sentence by sentence
  textSplit <- str_split(hotText,"[.]")
  # Unlisting the split so that it is a list of sentences
  textSplit <- unlist(textSplit)
  # Finding the sentence length
  sentLength <- length(textSplit)
  # Initializing a Document level DAG Consolidator
  docDag <- list()
  for(j in 1: sentLength){
    # Taking one sentence at a time
    textSamp <- textSplit[j]
    # Cleaning the sentence to get only the tokens
    cleantxtSplit <- revClean(textSamp)
    # Getting all the aspects together
    aspect = c("food","service","price","ambience")
    # Initiating a sentence DAG consolidatory
    sentDag <- list()
    for(k in aspect){
      # Getting the DAG for each aspect and storing in the sentence DAG consolidator
      sentDag[[length(sentDag)+1]] <- recScanner(cleantxtSplit,k)$dagStore
      
    } # End of loop which goes over each aspect within a sentence

    docDag[[length(docDag)+1]] <- sentDag
    
  } # End of the hierarchy at each sentence level
  
 hotDag[[length(hotDag)+1]] <- docDag
  
} # End of the Hierarchy at the Hotel level





```
# Tomorrow

The process side has a problem. If an aspect is as the last word, then the enList is found to be not working and there is an error.

Case : i = 6 , j = 12 , k = food
